// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeJy9QzV4HNi3p0eMLDz6GDEdvoK5A3Q',
    appId: '1:1017855760474:web:5f231fe716e9d047416063',
    messagingSenderId: '1017855760474',
    projectId: 'doctor-9518b',
    authDomain: 'doctor-9518b.firebaseapp.com',
    storageBucket: 'doctor-9518b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7OK0IJwhNnXUCt73g-Z9eUWGH9g6jRKs',
    appId: '1:1017855760474:android:bb6c01ac9ace8c7c416063',
    messagingSenderId: '1017855760474',
    projectId: 'doctor-9518b',
    storageBucket: 'doctor-9518b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2FRBho4gczhGaRY1UmeX00MHrtHqGeq0',
    appId: '1:1017855760474:ios:21cdae327a336e87416063',
    messagingSenderId: '1017855760474',
    projectId: 'doctor-9518b',
    storageBucket: 'doctor-9518b.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2FRBho4gczhGaRY1UmeX00MHrtHqGeq0',
    appId: '1:1017855760474:ios:21cdae327a336e87416063',
    messagingSenderId: '1017855760474',
    projectId: 'doctor-9518b',
    storageBucket: 'doctor-9518b.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSeJy9QzV4HNi3p0eMLDz6GDEdvoK5A3Q',
    appId: '1:1017855760474:web:ef3a5ba2035f9bbc416063',
    messagingSenderId: '1017855760474',
    projectId: 'doctor-9518b',
    authDomain: 'doctor-9518b.firebaseapp.com',
    storageBucket: 'doctor-9518b.appspot.com',
  );

}