// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3CrFH4Y7X6BUxMffBD9p_GjdzVrGntg',
    appId: '1:168528238029:web:ae837dd42bea9caa8ea084',
    messagingSenderId: '168528238029',
    projectId: 'test-4833d',
    authDomain: 'test-4833d.firebaseapp.com',
    storageBucket: 'test-4833d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdwbo-I3nbEQKTruxnTDSXHlV5h1ZEkVo',
    appId: '1:168528238029:android:d5dd4167a9f8725b8ea084',
    messagingSenderId: '168528238029',
    projectId: 'test-4833d',
    storageBucket: 'test-4833d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDA70D1pbjZGYeASgnMlc86dUGglh3iU',
    appId: '1:168528238029:ios:de76c402d9789ca28ea084',
    messagingSenderId: '168528238029',
    projectId: 'test-4833d',
    storageBucket: 'test-4833d.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDA70D1pbjZGYeASgnMlc86dUGglh3iU',
    appId: '1:168528238029:ios:de76c402d9789ca28ea084',
    messagingSenderId: '168528238029',
    projectId: 'test-4833d',
    storageBucket: 'test-4833d.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm3CrFH4Y7X6BUxMffBD9p_GjdzVrGntg',
    appId: '1:168528238029:web:55dcbb66822363ee8ea084',
    messagingSenderId: '168528238029',
    projectId: 'test-4833d',
    authDomain: 'test-4833d.firebaseapp.com',
    storageBucket: 'test-4833d.appspot.com',
  );
}
